version: "3"  
services:
  pandora:
    image: answerdev/answer:latest
    container_name: ${CONTAINER_NAME}
    restart: on-failure
    networks:  
      - 1panel-network
    volumes:
      - ./data:/data
    ports:
      - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:80
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
